spring:
  freemarker:
    request-context-attribute: req
    suffix: .html
    content-type: text/html
    enabled: true
    cache: false
    template-loader-path: classpath:/templates/
    charset: UTF-8
    settings:
      number_format: '0.##'
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://47.110.153.21:3306/diary?useUnicode=true&characterEncoding=utf-8&useSSL=false
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 9996